### ISSUE TITLE
Todo list for 0.1.1

### ISSUE THREAD

**Issue by jxnl** [jxnl/itpy#1]
- [x] support for reading it file types make sure to use `@classmethod`
  - [x] text by lines  `text_file()`
  - [x] csv by lines into lists, or tuples `csv_file()`
- [x] support for writing to different file types
- [x] seperate streaming logic out of `itpy.py` to `streaming/*.py` files that. `itpy.py` as it should only be for syntax.
- [x] implement sketching algorithms [sketching](http://en.wikipedia.org/wiki/Streaming_algorithm#Some_streaming_problems)
  - itpy.toSketch() to explicitly convert add addition functionality? `class SketchItpy(itpy):` ?
- [x] Implement our own data structures so there are less dependencies?
- [x] utils : functions like  lambda x:1, lambda x,y:x+y are pretty common we she should just have a cons, ones method in utils.
